### ISSUE TITLE
Add support to customize the launch and close messages

### ISSUE THREAD

**Issue by chadevanssf** [salesforce/violet-conversations#5]
Right now, there is a non-configurable launch and closing messages. For production use, we would need to be able to change those out.

Launch:
response.say(['Yes. How can I help?', 'Hey. Need me?', 'Yup. I am here.']);

Close:
violet.respondTo({name: 'closeSession', expecting: ["I am good", "No I am good", "Thanks", "Thank you"], resolve: (response) => { response.clearAllGoals(); response.endConversation(); }});

**Comment by vineet-sinha** [comment]
@chadevanssf - adding this support is definitely on our todo list.

Submitting a PR will help speed getting it in.
